namespace Glacier.Plot.Compute;

internal static class GpuPlotKernels
{
    public const string PtxSource = @"//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-37862127
// Cuda compilation tools, release 13.3, V13.3.33
// Based on NVVM 7.0.1
//

.version 9.3
.target sm_89
.address_size 64

	// .globl	plot_minmax_decimate_fp32

.visible .entry plot_minmax_decimate_fp32(
	.param .u64 plot_minmax_decimate_fp32_param_0,
	.param .u64 plot_minmax_decimate_fp32_param_1,
	.param .u64 plot_minmax_decimate_fp32_param_2,
	.param .u64 plot_minmax_decimate_fp32_param_3,
	.param .u32 plot_minmax_decimate_fp32_param_4,
	.param .u32 plot_minmax_decimate_fp32_param_5,
	.param .f32 plot_minmax_decimate_fp32_param_6
)
{
	.reg .pred 	%p<19>;
	.reg .f32 	%f<47>;
	.reg .b32 	%r<67>;
	.reg .b64 	%rd<32>;


	ld.param.u64 	%rd14, [plot_minmax_decimate_fp32_param_0];
	ld.param.u64 	%rd15, [plot_minmax_decimate_fp32_param_1];
	ld.param.u64 	%rd16, [plot_minmax_decimate_fp32_param_2];
	ld.param.u64 	%rd17, [plot_minmax_decimate_fp32_param_3];
	ld.param.u32 	%r28, [plot_minmax_decimate_fp32_param_4];
	ld.param.u32 	%r29, [plot_minmax_decimate_fp32_param_5];
	ld.param.f32 	%f16, [plot_minmax_decimate_fp32_param_6];
	cvta.to.global.u64 	%rd1, %rd17;
	cvta.to.global.u64 	%rd2, %rd16;
	cvta.to.global.u64 	%rd3, %rd15;
	mov.u32 	%r30, %ntid.x;
	mov.u32 	%r31, %ctaid.x;
	mov.u32 	%r32, %tid.x;
	mad.lo.s32 	%r1, %r31, %r30, %r32;
	setp.ge.s32 	%p1, %r1, %r29;
	@%p1 bra 	$L__BB0_12;

	cvt.rn.f32.s32 	%f17, %r1;
	mul.f32 	%f18, %f17, %f16;
	cvt.rzi.s32.f32 	%r2, %f18;
	add.s32 	%r33, %r1, 1;
	cvt.rn.f32.s32 	%f19, %r33;
	mul.f32 	%f20, %f19, %f16;
	cvt.rzi.s32.f32 	%r34, %f20;
	min.s32 	%r3, %r34, %r28;
	setp.ge.s32 	%p2, %r2, %r3;
	@%p2 bra 	$L__BB0_12;

	mul.wide.s32 	%rd18, %r2, 4;
	add.s64 	%rd19, %rd3, %rd18;
	ld.global.nc.f32 	%f45, [%rd19];
	add.s32 	%r57, %r2, 1;
	setp.ge.s32 	%p3, %r57, %r3;
	mov.f32 	%f46, %f45;
	mov.u32 	%r65, %r2;
	mov.u32 	%r66, %r2;
	@%p3 bra 	$L__BB0_9;

	mov.u32 	%r36, 2;
	sub.s32 	%r37, %r36, %r2;
	not.b32 	%r5, %r3;
	sub.s32 	%r38, %r37, %r5;
	and.b32  	%r56, %r38, 3;
	setp.eq.s32 	%p4, %r56, 0;
	mov.u32 	%r66, %r2;
	mov.u32 	%r65, %r2;
	mov.f32 	%f46, %f45;
	@%p4 bra 	$L__BB0_6;

	mul.wide.s32 	%rd20, %r57, 4;
	add.s64 	%rd30, %rd3, %rd20;
	mov.u32 	%r66, %r2;
	mov.u32 	%r65, %r2;
	mov.f32 	%f46, %f45;

$L__BB0_5:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f22, [%rd30];
	setp.lt.f32 	%p5, %f22, %f45;
	selp.f32 	%f45, %f22, %f45, %p5;
	selp.b32 	%r65, %r57, %r65, %p5;
	setp.gt.f32 	%p6, %f22, %f46;
	selp.f32 	%f46, %f22, %f46, %p6;
	selp.b32 	%r66, %r57, %r66, %p6;
	add.s32 	%r57, %r57, 1;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r56, %r56, -1;
	setp.ne.s32 	%p7, %r56, 0;
	@%p7 bra 	$L__BB0_5;

$L__BB0_6:
	mov.u32 	%r39, -3;
	sub.s32 	%r40, %r39, %r2;
	sub.s32 	%r41, %r40, %r5;
	setp.lt.u32 	%p8, %r41, 3;
	@%p8 bra 	$L__BB0_9;

	mul.wide.s32 	%rd21, %r57, 4;
	add.s64 	%rd22, %rd3, %rd21;
	add.s64 	%rd31, %rd22, 8;

$L__BB0_8:
	ld.global.nc.f32 	%f23, [%rd31+-8];
	setp.lt.f32 	%p9, %f23, %f45;
	selp.f32 	%f24, %f23, %f45, %p9;
	selp.b32 	%r42, %r57, %r65, %p9;
	setp.gt.f32 	%p10, %f23, %f46;
	selp.f32 	%f25, %f23, %f46, %p10;
	selp.b32 	%r43, %r57, %r66, %p10;
	ld.global.nc.f32 	%f26, [%rd31+-4];
	setp.lt.f32 	%p11, %f26, %f24;
	selp.f32 	%f27, %f26, %f24, %p11;
	add.s32 	%r44, %r57, 1;
	selp.b32 	%r45, %r44, %r42, %p11;
	setp.gt.f32 	%p12, %f26, %f25;
	selp.f32 	%f28, %f26, %f25, %p12;
	selp.b32 	%r46, %r44, %r43, %p12;
	ld.global.nc.f32 	%f29, [%rd31];
	setp.lt.f32 	%p13, %f29, %f27;
	selp.f32 	%f30, %f29, %f27, %p13;
	add.s32 	%r47, %r57, 2;
	selp.b32 	%r48, %r47, %r45, %p13;
	setp.gt.f32 	%p14, %f29, %f28;
	selp.f32 	%f31, %f29, %f28, %p14;
	selp.b32 	%r49, %r47, %r46, %p14;
	ld.global.nc.f32 	%f32, [%rd31+4];
	setp.lt.f32 	%p15, %f32, %f30;
	selp.f32 	%f45, %f32, %f30, %p15;
	add.s32 	%r50, %r57, 3;
	selp.b32 	%r65, %r50, %r48, %p15;
	setp.gt.f32 	%p16, %f32, %f31;
	selp.f32 	%f46, %f32, %f31, %p16;
	selp.b32 	%r66, %r50, %r49, %p16;
	add.s64 	%rd31, %rd31, 16;
	add.s32 	%r57, %r57, 4;
	setp.lt.s32 	%p17, %r57, %r3;
	@%p17 bra 	$L__BB0_8;

$L__BB0_9:
	cvta.to.global.u64 	%rd23, %rd14;
	mul.wide.s32 	%rd24, %r65, 4;
	add.s64 	%rd10, %rd23, %rd24;
	shl.b32 	%r51, %r1, 1;
	mul.wide.s32 	%rd25, %r51, 4;
	add.s64 	%rd11, %rd2, %rd25;
	add.s64 	%rd12, %rd1, %rd25;
	mul.wide.s32 	%rd26, %r66, 4;
	add.s64 	%rd13, %rd23, %rd26;
	setp.gt.s32 	%p18, %r65, %r66;
	@%p18 bra 	$L__BB0_11;
	bra.uni 	$L__BB0_10;

$L__BB0_11:
	ld.global.nc.f32 	%f35, [%rd13];
	st.global.f32 	[%rd11], %f35;
	st.global.f32 	[%rd12], %f46;
	ld.global.nc.f32 	%f36, [%rd10];
	add.s32 	%r52, %r1, %r1;
	mul.wide.s32 	%rd27, %r52, 4;
	add.s64 	%rd28, %rd2, %rd27;
	st.global.f32 	[%rd28+4], %f36;
	add.s64 	%rd29, %rd1, %rd27;
	st.global.f32 	[%rd29+4], %f45;
	bra.uni 	$L__BB0_12;

$L__BB0_10:
	ld.global.nc.f32 	%f33, [%rd10];
	st.global.f32 	[%rd11], %f33;
	st.global.f32 	[%rd12], %f45;
	ld.global.nc.f32 	%f34, [%rd13];
	st.global.f32 	[%rd11+4], %f34;
	st.global.f32 	[%rd12+4], %f46;

$L__BB0_12:
	ret;

}
	// .globl	plot_transform_coords_fp32
.visible .entry plot_transform_coords_fp32(
	.param .u64 plot_transform_coords_fp32_param_0,
	.param .u64 plot_transform_coords_fp32_param_1,
	.param .u64 plot_transform_coords_fp32_param_2,
	.param .u64 plot_transform_coords_fp32_param_3,
	.param .u32 plot_transform_coords_fp32_param_4,
	.param .f32 plot_transform_coords_fp32_param_5,
	.param .f32 plot_transform_coords_fp32_param_6,
	.param .f32 plot_transform_coords_fp32_param_7,
	.param .f32 plot_transform_coords_fp32_param_8,
	.param .f32 plot_transform_coords_fp32_param_9,
	.param .f32 plot_transform_coords_fp32_param_10
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<78>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<49>;


	ld.param.u64 	%rd29, [plot_transform_coords_fp32_param_0];
	ld.param.u64 	%rd30, [plot_transform_coords_fp32_param_1];
	ld.param.u64 	%rd31, [plot_transform_coords_fp32_param_2];
	ld.param.u64 	%rd32, [plot_transform_coords_fp32_param_3];
	ld.param.u32 	%r10, [plot_transform_coords_fp32_param_4];
	ld.param.f32 	%f1, [plot_transform_coords_fp32_param_5];
	ld.param.f32 	%f2, [plot_transform_coords_fp32_param_6];
	ld.param.f32 	%f3, [plot_transform_coords_fp32_param_7];
	ld.param.f32 	%f4, [plot_transform_coords_fp32_param_8];
	ld.param.f32 	%f5, [plot_transform_coords_fp32_param_9];
	ld.param.f32 	%f6, [plot_transform_coords_fp32_param_10];
	cvta.to.global.u64 	%rd1, %rd32;
	cvta.to.global.u64 	%rd2, %rd30;
	cvta.to.global.u64 	%rd3, %rd31;
	cvta.to.global.u64 	%rd4, %rd29;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r14, %r12, %r11, %r13;
	shl.b32 	%r1, %r14, 2;
	or.b32  	%r15, %r1, 3;
	setp.lt.s32 	%p1, %r15, %r10;
	@%p1 bra 	$L__BB1_8;
	bra.uni 	$L__BB1_1;

$L__BB1_8:
	mul.wide.s32 	%rd36, %r1, 4;
	add.s64 	%rd37, %rd4, %rd36;
	ld.global.nc.v4.f32 	{%f42, %f43, %f44, %f45}, [%rd37];
	add.s64 	%rd38, %rd2, %rd36;
	ld.global.nc.v4.f32 	{%f50, %f51, %f52, %f53}, [%rd38];
	sub.f32 	%f58, %f42, %f1;
	sub.f32 	%f59, %f43, %f1;
	sub.f32 	%f60, %f44, %f1;
	sub.f32 	%f61, %f45, %f1;
	sub.f32 	%f62, %f50, %f2;
	mul.f32 	%f63, %f62, %f4;
	sub.f32 	%f64, %f51, %f2;
	mul.f32 	%f65, %f64, %f4;
	sub.f32 	%f66, %f52, %f2;
	mul.f32 	%f67, %f66, %f4;
	sub.f32 	%f68, %f53, %f2;
	mul.f32 	%f69, %f68, %f4;
	add.s64 	%rd39, %rd3, %rd36;
	fma.rn.f32 	%f70, %f61, %f3, %f5;
	fma.rn.f32 	%f71, %f60, %f3, %f5;
	fma.rn.f32 	%f72, %f59, %f3, %f5;
	fma.rn.f32 	%f73, %f58, %f3, %f5;
	st.global.v4.f32 	[%rd39], {%f73, %f72, %f71, %f70};
	add.s64 	%rd40, %rd1, %rd36;
	sub.f32 	%f74, %f6, %f69;
	sub.f32 	%f75, %f6, %f67;
	sub.f32 	%f76, %f6, %f65;
	sub.f32 	%f77, %f6, %f63;
	st.global.v4.f32 	[%rd40], {%f77, %f76, %f75, %f74};
	bra.uni 	$L__BB1_9;

$L__BB1_1:
	setp.ge.s32 	%p2, %r1, %r10;
	@%p2 bra 	$L__BB1_9;

	and.b32  	%r19, %r10, 3;
	setp.eq.s32 	%p3, %r19, 0;
	mov.u32 	%r20, %r1;
	@%p3 bra 	$L__BB1_5;

	mul.wide.s32 	%rd33, %r1, 4;
	add.s64 	%rd44, %rd1, %rd33;
	add.s64 	%rd43, %rd2, %rd33;
	add.s64 	%rd42, %rd3, %rd33;
	add.s64 	%rd41, %rd4, %rd33;
	mov.u32 	%r20, %r1;

$L__BB1_4:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f7, [%rd41];
	sub.f32 	%f8, %f7, %f1;
	fma.rn.f32 	%f9, %f8, %f3, %f5;
	st.global.f32 	[%rd42], %f9;
	ld.global.nc.f32 	%f10, [%rd43];
	sub.f32 	%f11, %f10, %f2;
	mul.f32 	%f12, %f11, %f4;
	sub.f32 	%f13, %f6, %f12;
	st.global.f32 	[%rd44], %f13;
	add.s32 	%r20, %r20, 1;
	add.s64 	%rd44, %rd44, 4;
	add.s64 	%rd43, %rd43, 4;
	add.s64 	%rd42, %rd42, 4;
	add.s64 	%rd41, %rd41, 4;
	add.s32 	%r19, %r19, -1;
	setp.ne.s32 	%p4, %r19, 0;
	@%p4 bra 	$L__BB1_4;

$L__BB1_5:
	not.b32 	%r16, %r1;
	add.s32 	%r17, %r16, %r10;
	setp.lt.u32 	%p5, %r17, 3;
	@%p5 bra 	$L__BB1_9;

	mul.wide.s32 	%rd34, %r20, 4;
	add.s64 	%rd35, %rd34, 8;
	add.s64 	%rd48, %rd4, %rd35;
	add.s64 	%rd47, %rd3, %rd35;
	add.s64 	%rd46, %rd2, %rd35;
	add.s64 	%rd45, %rd1, %rd35;

$L__BB1_7:
	ld.global.nc.f32 	%f14, [%rd48+-8];
	sub.f32 	%f15, %f14, %f1;
	fma.rn.f32 	%f16, %f15, %f3, %f5;
	st.global.f32 	[%rd47+-8], %f16;
	ld.global.nc.f32 	%f17, [%rd46+-8];
	sub.f32 	%f18, %f17, %f2;
	mul.f32 	%f19, %f18, %f4;
	sub.f32 	%f20, %f6, %f19;
	st.global.f32 	[%rd45+-8], %f20;
	ld.global.nc.f32 	%f21, [%rd48+-4];
	sub.f32 	%f22, %f21, %f1;
	fma.rn.f32 	%f23, %f22, %f3, %f5;
	ld.global.nc.f32 	%f24, [%rd46+-4];
	sub.f32 	%f25, %f24, %f2;
	mul.f32 	%f26, %f25, %f4;
	sub.f32 	%f27, %f6, %f26;
	ld.global.nc.f32 	%f28, [%rd48];
	sub.f32 	%f29, %f28, %f1;
	fma.rn.f32 	%f30, %f29, %f3, %f5;
	st.global.f32 	[%rd47+-4], %f23;
	st.global.f32 	[%rd45+-4], %f27;
	ld.global.nc.f32 	%f31, [%rd46];
	sub.f32 	%f32, %f31, %f2;
	mul.f32 	%f33, %f32, %f4;
	sub.f32 	%f34, %f6, %f33;
	st.global.f32 	[%rd47], %f30;
	ld.global.nc.f32 	%f35, [%rd48+4];
	sub.f32 	%f36, %f35, %f1;
	fma.rn.f32 	%f37, %f36, %f3, %f5;
	ld.global.nc.f32 	%f38, [%rd46+4];
	sub.f32 	%f39, %f38, %f2;
	mul.f32 	%f40, %f39, %f4;
	sub.f32 	%f41, %f6, %f40;
	st.global.f32 	[%rd45], %f34;
	st.global.f32 	[%rd47+4], %f37;
	st.global.f32 	[%rd45+4], %f41;
	add.s64 	%rd48, %rd48, 16;
	add.s64 	%rd47, %rd47, 16;
	add.s64 	%rd46, %rd46, 16;
	add.s64 	%rd45, %rd45, 16;
	add.s32 	%r20, %r20, 4;
	setp.lt.s32 	%p6, %r20, %r10;
	@%p6 bra 	$L__BB1_7;

$L__BB1_9:
	ret;

}
	// .globl	plot_lttb_bucket_averages_fp32
.visible .entry plot_lttb_bucket_averages_fp32(
	.param .u64 plot_lttb_bucket_averages_fp32_param_0,
	.param .u64 plot_lttb_bucket_averages_fp32_param_1,
	.param .u64 plot_lttb_bucket_averages_fp32_param_2,
	.param .u64 plot_lttb_bucket_averages_fp32_param_3,
	.param .u32 plot_lttb_bucket_averages_fp32_param_4,
	.param .u32 plot_lttb_bucket_averages_fp32_param_5,
	.param .f32 plot_lttb_bucket_averages_fp32_param_6
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<18>;
	.reg .b32 	%r<29>;
	.reg .f64 	%fd<49>;
	.reg .b64 	%rd<31>;


	ld.param.u64 	%rd19, [plot_lttb_bucket_averages_fp32_param_0];
	ld.param.u64 	%rd20, [plot_lttb_bucket_averages_fp32_param_1];
	ld.param.u64 	%rd17, [plot_lttb_bucket_averages_fp32_param_2];
	ld.param.u64 	%rd18, [plot_lttb_bucket_averages_fp32_param_3];
	ld.param.u32 	%r13, [plot_lttb_bucket_averages_fp32_param_4];
	ld.param.u32 	%r14, [plot_lttb_bucket_averages_fp32_param_5];
	ld.param.f32 	%f1, [plot_lttb_bucket_averages_fp32_param_6];
	cvta.to.global.u64 	%rd1, %rd20;
	cvta.to.global.u64 	%rd2, %rd19;
	mov.u32 	%r15, %ntid.x;
	mov.u32 	%r16, %ctaid.x;
	mov.u32 	%r17, %tid.x;
	mad.lo.s32 	%r1, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r14;
	@%p1 bra 	$L__BB2_10;

	cvt.rn.f32.s32 	%f2, %r1;
	mul.f32 	%f3, %f2, %f1;
	cvt.rzi.s32.f32 	%r2, %f3;
	add.s32 	%r18, %r1, 1;
	cvt.rn.f32.s32 	%f4, %r18;
	mul.f32 	%f5, %f4, %f1;
	cvt.rzi.s32.f32 	%r19, %f5;
	min.s32 	%r3, %r19, %r13;
	setp.gt.s32 	%p2, %r3, %r2;
	cvta.to.global.u64 	%rd21, %rd17;
	mul.wide.s32 	%rd22, %r1, 4;
	add.s64 	%rd3, %rd21, %rd22;
	cvta.to.global.u64 	%rd23, %rd18;
	add.s64 	%rd4, %rd23, %rd22;
	@%p2 bra 	$L__BB2_3;
	bra.uni 	$L__BB2_2;

$L__BB2_3:
	sub.s32 	%r4, %r3, %r2;
	and.b32  	%r26, %r4, 3;
	setp.eq.s32 	%p3, %r26, 0;
	mov.f64 	%fd48, 0d0000000000000000;
	mov.u32 	%r27, %r2;
	mov.f64 	%fd47, %fd48;
	@%p3 bra 	$L__BB2_6;

	mul.wide.s32 	%rd24, %r2, 4;
	add.s64 	%rd28, %rd1, %rd24;
	add.s64 	%rd27, %rd2, %rd24;
	mov.f64 	%fd48, 0d0000000000000000;
	mov.u32 	%r27, %r2;

$L__BB2_5:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f6, [%rd27];
	cvt.f64.f32 	%fd20, %f6;
	add.f64 	%fd47, %fd47, %fd20;
	ld.global.nc.f32 	%f7, [%rd28];
	cvt.f64.f32 	%fd21, %f7;
	add.f64 	%fd48, %fd48, %fd21;
	add.s32 	%r27, %r27, 1;
	add.s64 	%rd28, %rd28, 4;
	add.s64 	%rd27, %rd27, 4;
	add.s32 	%r26, %r26, -1;
	setp.ne.s32 	%p4, %r26, 0;
	@%p4 bra 	$L__BB2_5;

$L__BB2_6:
	not.b32 	%r21, %r3;
	mov.u32 	%r22, -2;
	sub.s32 	%r23, %r22, %r2;
	sub.s32 	%r24, %r23, %r21;
	setp.lt.u32 	%p5, %r24, 3;
	@%p5 bra 	$L__BB2_9;

	mul.wide.s32 	%rd25, %r27, 4;
	add.s64 	%rd26, %rd25, 8;
	add.s64 	%rd30, %rd2, %rd26;
	add.s64 	%rd29, %rd1, %rd26;

$L__BB2_8:
	ld.global.nc.f32 	%f8, [%rd30+-8];
	cvt.f64.f32 	%fd22, %f8;
	add.f64 	%fd23, %fd47, %fd22;
	ld.global.nc.f32 	%f9, [%rd29+-8];
	cvt.f64.f32 	%fd24, %f9;
	add.f64 	%fd25, %fd48, %fd24;
	ld.global.nc.f32 	%f10, [%rd30+-4];
	cvt.f64.f32 	%fd26, %f10;
	add.f64 	%fd27, %fd23, %fd26;
	ld.global.nc.f32 	%f11, [%rd29+-4];
	cvt.f64.f32 	%fd28, %f11;
	add.f64 	%fd29, %fd25, %fd28;
	ld.global.nc.f32 	%f12, [%rd30];
	cvt.f64.f32 	%fd30, %f12;
	add.f64 	%fd31, %fd27, %fd30;
	ld.global.nc.f32 	%f13, [%rd29];
	cvt.f64.f32 	%fd32, %f13;
	add.f64 	%fd33, %fd29, %fd32;
	ld.global.nc.f32 	%f14, [%rd30+4];
	cvt.f64.f32 	%fd34, %f14;
	add.f64 	%fd47, %fd31, %fd34;
	ld.global.nc.f32 	%f15, [%rd29+4];
	cvt.f64.f32 	%fd35, %f15;
	add.f64 	%fd48, %fd33, %fd35;
	add.s64 	%rd30, %rd30, 16;
	add.s64 	%rd29, %rd29, 16;
	add.s32 	%r27, %r27, 4;
	setp.lt.s32 	%p6, %r27, %r3;
	@%p6 bra 	$L__BB2_8;

$L__BB2_9:
	cvt.rn.f64.s32 	%fd36, %r4;
	div.rn.f64 	%fd37, %fd47, %fd36;
	cvt.rn.f32.f64 	%f16, %fd37;
	st.global.f32 	[%rd3], %f16;
	div.rn.f64 	%fd38, %fd48, %fd36;
	cvt.rn.f32.f64 	%f17, %fd38;
	st.global.f32 	[%rd4], %f17;
	bra.uni 	$L__BB2_10;

$L__BB2_2:
	mov.u32 	%r20, 0;
	st.global.u32 	[%rd3], %r20;
	st.global.u32 	[%rd4], %r20;

$L__BB2_10:
	ret;

}

";
}